.TH XHHPC 1 "27 Dec 2018" "0.3.1" "User Manual"
.SH NAME
xhhpc \- hide the mouse pointer in X
.SH DESCRIPTION
\fBxhhpc\fP is a small program to hide the mouse pointer within X sessions.
.SH SYNOPSIS
.B xhhpc
.RI [ options ]
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-i
number of seconds to wait before hiding the pointer
.TP
.B \-v
turn on verbose mode.
.SH AUTHORS
Copyright (c) 2013 Nicolas Hillegeer <nicolas at hillegeer dot com>

All rights reserved.
.SH SEE ALSO
xorg (1)
